### ISSUE TITLE
AddPiece should accept an io.Reader

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-sectorbuilder#2]
`AddPiece` should allow the caller to pass in a reader for the data they are wanting to add. Requiring a filepath is really cumbersome

**Comment by laser** [comment]
You can’t pass a Go reader through the FFI to Rust. To work around this limitation while supporting streaming, Rust accepts a file path. We make the caller translate from Reader to path. 

For example: go-filecoin wraps the CGO AddPiece function with some software which accepts a Reader, creates a fifo pipe to which the reader’s bytes are copied, and passes that pipe’s path through the FFI. 

See: https://github.com/filecoin-project/go-filecoin/blob/master/proofs/sectorbuilder/rustsectorbuilder.go#L90

I don’t think this fifo business belongs in the CGO bindings library. You could either take inspiration from go-Filecoin (and do the Reader to fifo song yourself) or propose an FFI compatible Rust API that doesn’t use paths but does support streaming.

Thoughts?

**Comment by whyrusleeping** [comment]
Just have the ffi accept a file descriptor, on the go bindings side we can create a pipe (https://golang.org/pkg/os/#Pipe) and then pass the bare fd down: https://golang.org/pkg/os/#File.Fd

The go side can then `io.Copy` everything into their end of the pipe, then close it, and the rust side can read out the end of the pipe they were given. Should work fine, since file descriptors are a system level thing, they can def be shared between ffi.

If/when we move to having proving stuff be a separate process, we can even pass file descriptors to other processes (on unix systems) with SendFd (example: https://github.com/whyrusleeping/hellabot/blob/master/recon_linux.go)

**Comment by laser** [comment]
@whyrusleeping 

> Just have the ffi accept a file descriptor

If we did what you propose, we'd be moving farther away from Windows support.

> The go side can then io.Copy everything into their end of the pipe, then close it,

How do we keep Go from [GCing the `File` and rendering the descriptor invalid?](https://golang.org/pkg/os/#File.Fd) before Rust is done with it?

> we can even pass file descriptors to other processes (on unix systems)

What benefit do you see to sharing file descriptors between processes over sharing file paths between processes?

**Comment by whyrusleeping** [comment]
> If we did what you propose, we'd be moving farther away from Windows support.

No, pipe is supported on all platforms go compiles on

> How do we keep Go from GCing the File and rendering the descriptor invalid? before Rust is done with it?

The go side holds the reference to the pipe for the duration of the transfer. Theres no risk here.

> What benefit do you see to sharing file descriptors between processes over sharing file paths between processes?

Note: i don't expect us to do this, it would be better to just use the unix domain socket directly instead of using it to pass the file descriptor, just an idea thrown into the brainstorm pile

**Comment by laser** [comment]
> No, pipe is supported on all platforms go compiles on

`os.Pipe` is supported on all platforms that Golang compiles on. `File#Fd`, used to produce the file descriptor from the read side of the pipe, [does not](https://golang.org/src/os/file_unix.go?s=1887:1914#L5). This is unsurprising, as Windows doesn't use file descriptors (but rather `HANDLE`).

**Comment by whyrusleeping** [comment]
Looks fine to me: https://golang.org/src/os/file_windows.go?s=808:937

**Comment by laser** [comment]
Well I'll be damned. `File#Fd` returns a file descriptor in Unix-like environments... and a HANDLE in Windows. Interesting choice for a method name. You win!

**Comment by whyrusleeping** [comment]
@laser arent you taking a day off?

**Comment by Kubuxu** [comment]
In short regarding keeping things alive (forcing Go not to close file descriptor).

You have to call `runtime.KeepAlive` after Rust is done with using the file. 

So:
```go
func AddPiece(f os.File) error {
    fd := f.Fd()
    error := C.AddPiece(fd)
    runtime.KeepAlive(f)
}
```
If AddPiece on the side of Rust is synchronous. If it is async, you will have to do something similar but keep the `os.File` around to be able to call `runtime.KeepAlive(f)` after rust is done with it.

**Comment by laser** [comment]
> If AddPiece on the side of Rust is synchronous.

The `C.add_piece` function reads to the end of the provided file (by path) before returning. If you can keep the GC from cleaning up the file descriptor before that function call returns, then we'll be good. Thanks for following up @Kubuxu.

**Comment by Kubuxu** [comment]
Then the pseudocode above should work.

**Comment by laser** [comment]
A thing to consider: Passing a file descriptor from the Filecoin node to the proving library implies that the Filecoin node and proving library are running on the same machine. 

This is not a property of the existing, file path-based approach; the Filecoin node running on host A may provide the proving system running on host B with a (shared) NFS path.

**Comment by Kubuxu** [comment]
We can always make both available.

**Comment by dignifiedquire** [comment]
I talked with @laser and for now we will switch to accepting an `os.File`, when we have a distributed thing, we can always add an api for paths back.
