### ISSUE TITLE
Why does the sealseed ticket have to be a Fr?

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-sectorbuilder#43]
I'm getting this error when passing chain randomness as the ticket: "Bytes could not be converted to Fr"

cc @dignifiedquire

**Comment by porcuquine** [comment]
@dignifiedquire I think we're using this as input to a Blake2s hash, so any 32 bytes should work. If that's a problem, we can truncate, but it would be good to know why it's necessary and would need to go into the spec. I think this might just be a leftover from when you recently switched this from pedersen.
